### ISSUE TITLE
Are you open to accepting the API from a different kernel?

### ISSUE THREAD

**Issue by xxnuo** [obgnail/clash-api#2]
The Clash kernel is dead, prompting my switch to the [Mihomo kernel](https://github.com/MetaCubeX/mihomo/tree/Alpha) for the development of the API. 
You can find the api docs here [https://wiki.metacubex.one/api](https://wiki.metacubex.one/api)

I intend to use these apis in a Go project.

Should you approve the API update using this kernel, I'll submit pull requests (PRs) for it. If not, I'll proceed to update it within my forked repository.

**Comment by obgnail** [comment]
@xxnuo 

sure

embrace change  it is the only constant in life

 I appreciate your support very much
