### ISSUE TITLE
selector 请问这个值如何得到呢？谢谢

### ISSUE THREAD

**Issue by zwhmaybe** [obgnail/clash-api#4]
selector 请问这个值如何得到呢？谢谢
![微信截图_20240620151555](https://github.com/obgnail/clash-api/assets/23068110/9e1476ed-f5fe-4f90-b532-7b13b2883244)

**Comment by zwhmaybe** [comment]
或者说，通过api切换节点 该如何操作呢，我是python，谢谢

**Comment by obgnail** [comment]
我这个项目是 golang 的呀，和 python 没有关系呀

```go
clash.SwitchProxy("🍃 Proxies", "冷门 俄罗斯")
```

![IMG_2024-06-20_15-40-32](https://github.com/obgnail/clash-api/assets/48992887/084483d1-9040-40c0-9a09-7ac9c22ecb2e)

**Comment by zwhmaybe** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zwhmaybe** [comment]
没有 proxy-groups 的话，2个是否都可以是图上的  Name1？

**Comment by obgnail** [comment]
不清楚，你试试呗。

这个项目纯粹是将 clash document 翻译成 golang 代码，我也不清楚其中的各项细节，我是看文档摸索出来的。

我在 proxies 标签中是可以看到有 selector 的。

![IMG_2024-06-20_17-08-13 (1)](https://github.com/obgnail/clash-api/assets/48992887/6f467c80-6fca-4349-aede-58dbbc3e52f2)

**Comment by zwhmaybe** [comment]
谢谢您~
